title: Dalmend Home
description: Premium home decor and interior design
theme: minima
baseurl: "/dalmend-home"
url: "https://siavashsed.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
